add some logging to csrgrinder

diff --git a/csrgrinder b/csrgrinder
--- a/csrgrinder
+++ b/csrgrinder
@@ -9,13 +9,20 @@
 STDIN=$(cat)
 CSRFILE=$(mktemp)
 echo "$STDIN" > $CSRFILE
+logger "Wrote $(stat -c%s $CSRFILE) bytes CSR from client $SSH_CLIENT to temp file $CSRFILE"
 
 # get a temp filename for the certificate
 CERTFILE=$(mktemp)
 rm -f $CERTFILE
 
 # issue new certificate
+logger "Running certbot..."
 sudo /usr/local/bin/certbot certonly --non-interactive --quiet --config /usr/local/etc/letsencrypt/letsencrypt.ini --csr $CSRFILE --fullchain-path $CERTFILE
+if [ $? -eq 0 ]; then
+    logger "Success. Certbot wrote $(stat -c%s $CERTFILE) bytes certificate chain to $CERTFILE - sending to stdout and cleaning up temp files"
+else
+    logger "Failure. Certbot exit code was $?"
+fi
 
 # output certificate to stdout
 cat $CERTFILE
